#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar  9 17:38:22 2026

@author: kzhavoronko
"""

import numpy as np
import matplotlib.pyplot as plt

def créer_mlp(nb_neurone_par_couche, fonction_couche, derivé_fonction_couche, theta_initial, dim_entree):
    reseaux = {
        "couche": nb_neurone_par_couche,
        "fonction": fonction_couche,
        "dérivé_fonction": derivé_fonction_couche,
        "Theta": [], # On stocke les matrices ici
        "valeur_Z": [],
        "valeur_fonction": [],
        "deltas": []
    }
    
    # On transforme tes listes de listes 'theta_initial' en matrices NumPy propres
    for matrix in theta_initial:
        reseaux["Theta"].append(np.array(matrix, dtype=float))
        
    return reseaux

def propa_globale(X, reseaux):
    """Calcule la sortie du réseau pour une entrée X (vectorisé)"""
    activation = np.array(X)
    reseaux["valeur_fonction"] = [activation] 
    reseaux["valeur_Z"] = []
    
    for i in range(len(reseaux["couche"])):
        # Ajout du biais (1) à l'activation précédente
        entree_avec_biais = np.append(activation, 1.0)
        
        # Z = W * X (Vectorisé : remplace ta fonction z)
        z = np.dot(reseaux["Theta"][i], entree_avec_biais)
        activation = reseaux["fonction"][i](z)
        
        reseaux["valeur_Z"].append(z)
        reseaux["valeur_fonction"].append(activation)
    return activation

def delta_global(data, reseaux):
    """Calcule tous les deltas du réseau pour un couple (X, Y)"""
    X, Y_cible = data
    propa_globale(X, reseaux)
    
    # 1. Delta de la dernière couche
    z_L = reseaux["valeur_Z"][-1]
    a_L = reseaux["valeur_fonction"][-1]
    delta = (a_L - np.array(Y_cible)) * reseaux["dérivé_fonction"][-1](z_L)
    
    deltas = [delta]
    
    # 2. Descente à travers les couches (Retropropagation vectorisée)
    for i in reversed(range(len(reseaux["couche"]) - 1)):
        # On ignore la colonne du biais pour propager l'erreur
        W_sans_biais = reseaux["Theta"][i+1][:, :-1]
        z_curr = reseaux["valeur_Z"][i]
        
        # Formule matricielle du delta
        delta = np.dot(W_sans_biais.T, delta) * reseaux["dérivé_fonction"][i](z_curr)
        deltas.insert(0, delta)
        
    reseaux["deltas"] = deltas
    return deltas

def gradient(data_list, reseaux):
    """Calcule le gradient moyen sur tout le dataset (vectorisé)"""
    grad_total = [np.zeros_like(W) for W in reseaux["Theta"]]
    
    for D in data_list:
        delta_global(D, reseaux)
        
        for i in range(len(reseaux["Theta"])):
            # On récupère l'activation qui est entrée dans cette couche (avec le biais)
            activation_prec = np.append(reseaux["valeur_fonction"][i], 1.0)
            
            # Produit extérieur (outer product) remplace tes boucles imbriquées
            grad_total[i] += np.outer(reseaux["deltas"][i], activation_prec)
            
    # Moyenne du gradient
    return [g / len(data_list) for g in grad_total]

def gradient_a_pas_constant(data, reseaux):
    n_max = 2000
    eta = 0.1
    couts = []

    for _ in range(n_max):
        grads = gradient(data, reseaux)
        
        # Mise à jour des poids
        for i in range(len(reseaux["Theta"])):
            reseaux["Theta"][i] -= eta * grads[i]
            
        # Calcul du coût moyen pour l'affichage
        c = sum(0.5 * np.sum((propa_globale(X, reseaux) - Y)**2) for X, Y in data) / len(data)
        couts.append(c)

    plt.plot(couts)
    plt.title("Évolution du coût (Vectorisé)")
    plt.show()

# --- EXEMPLE DE TEST ---
# 1 entrée, 2 neurones cachés, 1 sortie
W1 = [[0.8, 0.1], [-0.4, 0.2]] # [w, biais]
W2 = [[0.7, 0.5, -0.3]]        # [v1, v2, biais_out]

sigmoid = lambda x: 1/(1+np.exp(-x))
derive_sigmoid = lambda x: sigmoid(x)*(1-sigmoid(x))
identite = lambda x: x
derive_identite = lambda x: np.ones_like(x)

MLP = créer_mlp([2, 1], [sigmoid, identite], [derive_sigmoid, derive_identite], [W1, W2], 1)
